## ----------------------- #
##      Main Configs       #
## ----------------------- #
#
url: http://openyourproject.hkw7.org/
title: Harlan T Wood
subtitle: chief integration officer of elightened structure
author:
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:
  
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

lsi: false

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
#root: /project

permalink: /pub/:title
#permalink: /blog/:year/:month/:day/:title/

#code_dir: downloads/code
#category_dir: blog/categories
markdown: maruku

#pygments: false # default python pygments have been replaced by pygments.rb
pygments: true

#paginate: 10          # Posts per page on the blog index
#pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: false       # Converts page and post titles to titlecase

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: harlantwood
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: true

# If the repo behind this site is stored on Github, you can specify
# your github repo name to allow people to fork your site:
# github_repo: xxx.github.com

# Twitter
twitter_user: harlantwood
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: false

# # Google +1
# google_plus_one: true
# google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 117965088231622732014
googleplus_hidden: true

# Pinboard
pinboard_user: onesunone
pinboard_count: 3

## Delicious
#delicious_user:
#delicious_count: 3
#
## Disqus Comments
#disqus_short_name:
#disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-17399272-1

# Facebook Like
facebook_like: false
